# Generated by Django 4.2.2 on 2023-06-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('surname', models.CharField(max_length=80)),
                ('age', models.PositiveIntegerField()),
                ('directions', models.CharField(choices=[('Фортепиано', 'Фортепиано'), ('Струнные инструменты', 'Струнные инструменты'), ('Духовые и ударные инструменты', 'Духовые и ударные инструменты')], max_length=100)),
                ('class_number', models.PositiveIntegerField()),
                ('tool', models.CharField(max_length=80)),
            ],
        ),
    ]
